---
- hosts: localhost
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - {import_role: name=system tasks_from=kernel, tags: ['kernel']}
    - {import_role: name=system tasks_from=base, tags: ['base']}
    #- {import_role: name=system tasks_from=network, tags: ['network']}
    #- {import_role: name=system tasks_from=fonts,   tags: ['fonts']}
    - {import_role: name=system tasks_from=gnome,   tags: ['gnome']}
    - {import_role: name=system tasks_from=userapps,   tags: ['userapps']}
