- name: userapps > User viny
  ansible.builtin.user:
    name: viny
    group: viny
    shell: /bin/zsh
    groups: uucp,wheel
    append: yes

- name: userapps > Install my favorite apps
  community.general.pacman: name={{ packages | join(',') }}
  vars:
    packages:
      - firefox
      - thunderbird,thunderbird-i18n-fr 
      - keepassxc
      - ncmpcpp
      - vlc

- name: userapps > Install base dev tools
  community.general.pacman: name={{ packages | join(',') }}
  vars:
    packages:
      - cmake
      - gdb
      - lcov
      - minicom
      - perf

- name: userapps > Install C++ dev tools
  community.general.pacman: name=heaptrack

- name: userapps > Install JRE OpenJDK
  community.general.pacman: name=jre-openjdk
